### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by kidandcat** [kidandcat/FeathersGO#1]
### TODO
- [x] Redis database per resource
- [x] Memory storage
- [ ] Clear memory storage
- [x] Generic database wrapper
- [x] Accept storage parameter (memory, redis, redisCluster, postgre)
- [ ] Accept ID parameter as queryString
- [ ] Allow set Key as parameter at creating
- [ ] Allow filters
- [ ] Pass Key size as config parameter
- [ ] Handle config file inexistence
- [ ] Handle error
- [ ] Hooks
- [x] Static, make / go to index.html
